CommonDefs.h: Drop likely macro
* this macro isn't used anywhere (only unlikely is)
* with boost 1.67.0 it conflicts with likely function in date_time added in:
  https://github.com/boostorg/date_time/commit/8b92513a947e6311854ac6d3b9519f175c93017d
  causing:
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-g++   -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/inc -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/Boost_INCLUDE_DIRS -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/luna-service2 -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/json-c -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/mojodb -m32 -march=i586  --sysroot=/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0=/usr/src/debug/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0 -fdebug-prefix-map=/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot= -fdebug-prefix-map=/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m32 -march=i586  --sysroot=/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot -fpermissive -DMOJ_LINUX -O -ggdb -Wuninitialized -Winit-self -Wl,--unresolved-symbols=ignore-in-shared-libs,-rpath-link,/lib -DWEBOS_TARGET_MACHINE_QEMUX86 -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/luna-service2 -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/json-c -I/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common       -DNDEBUG -MD -MT CMakeFiles/mojomail-imap.dir/src/commands/SyncEmailsCommand.cpp.o -MF CMakeFiles/mojomail-imap.dir/src/commands/SyncEmailsCommand.cpp.o.d -o CMakeFiles/mojomail-imap.dir/src/commands/SyncEmailsCommand.cpp.o -c /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/src/commands/SyncEmailsCommand.cpp
In file included from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/mojodb/core/MojVector.h:26,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/mojodb/core/MojSignal.h:26,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common/client/Command.h:22,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/inc/commands/ImapCommand.h:22,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/inc/commands/ImapSessionCommand.h:22,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/inc/commands/ImapSyncSessionCommand.h:22,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/inc/commands/SyncEmailsCommand.h:22,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/src/commands/SyncEmailsCommand.cpp:19:
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/mojodb/core/MojUtil.h:59:6: warning: redeclaration of 'template<class T, class COMP> void MojQuickSort(T*, MojSize, const COMP&)' may not have default arguments [-fpermissive]
 void MojQuickSort(T* array, MojSize numElems, const COMP& comp = COMP());
      ^~~~~~~~~~~~
In file included from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common/exceptions/MojErrException.h:22,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/inc/ImapCoreDefs.h:22,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/inc/commands/SyncEmailsCommand.h:24,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/src/commands/SyncEmailsCommand.cpp:19:
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common/CommonDefs.h:36:36: error: expected identifier before '(' token
 #define likely(x) __builtin_expect((x),1)
                                    ^
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common/CommonDefs.h:36:40: error: expected identifier before numeric constant
 #define likely(x) __builtin_expect((x),1)
                                        ^
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common/CommonDefs.h:36:40: error: expected ',' or '...' before numeric constant
In file included from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/format_date_parser.hpp:17,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/date_generator_parser.hpp:20,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/date_facet.hpp:25,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/gregorian/gregorian_io.hpp:16,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/gregorian/gregorian.hpp:31,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/posix_time/time_formatters.hpp:12,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/posix_time/posix_time.hpp:24,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/src/commands/SyncEmailsCommand.cpp:20:
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/special_values_parser.hpp: In static member function 'static bool boost::date_time::special_values_parser<date_type, charT>::__builtin_expect(int (*)(const string_type&), int)':
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/special_values_parser.hpp:107:14: error: 'str' was not declared in this scope
         if (!str.empty()) {
              ^~~
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/special_values_parser.hpp:107:14: note: suggested alternative: 'std'
         if (!str.empty()) {
              ^~~
              std
In file included from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common/exceptions/MojErrException.h:22,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/inc/ImapCoreDefs.h:22,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/inc/commands/SyncEmailsCommand.h:24,
                 from /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/git/imap/src/commands/SyncEmailsCommand.cpp:19:
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/time_parsing.hpp: In instantiation of 'time_type boost::date_time::parse_iso_time(const string&, char) [with time_type = boost::posix_time::ptime; std::__cxx11::string = std::__cxx11::basic_string<char>]':
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/boost/date_time/posix_time/time_parsers.hpp:35:51:   required from here
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common/CommonDefs.h:36:35: error: no matching function for call to 'boost::date_time::special_values_parser<boost::gregorian::date, char>::__builtin_expect(const string&, int)'
 #define likely(x) __builtin_expect((x),1)
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common/CommonDefs.h:36:19: note: candidate: 'static bool boost::date_time::special_values_parser<date_type, charT>::__builtin_expect(int (*)(const string_type&), int) [with date_type = boost::gregorian::date; charT = char; boost::date_time::special_values_parser<date_type, charT>::string_type = std::__cxx11::basic_string<char>]'
 #define likely(x) __builtin_expect((x),1)
                   ^~~~~~~~~~~~~~~~
/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/mojomail-imap/2.0.0-99+gitAUTOINC+e4e26323af-r0/recipe-sysroot/usr/include/email-common/CommonDefs.h:36:19: note:   no known conversion for argument 1 from 'const string' {aka 'const std::__cxx11::basic_string<char>'} to 'int (*)(const string_type&)' {aka 'int (*)(const std::__cxx11::basic_string<char>&)'}
ninja: build stopped: subcommand failed.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>